[build]
builder = "Nixpacks"
sourceDir = "backend"

[build.nixpacks]
buildCmd = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "./start.sh"
