services:
  - type: web
    name: red-product-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d33togje5dus73ehhkjg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: red_product_db
      - key: DB_USERNAME
        value: red_product_db_user
      - key: DB_PASSWORD
        value: SDwewxuvvC1C3CBkvqY9bjhsj8NDXcnj
