services:
  - type: web
    name: red-product-backend
    runtime: php
    rootDir: backend
    buildCommand: './build.sh'
    startCommand: './start.sh'
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromSecret: db_host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromSecret: db_name
      - key: DB_USERNAME
        fromSecret: db_username
      - key: DB_PASSWORD
        fromSecret: db_password
