[phases.setup]
nixPkgs = ["php82", "composer"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan key:generate",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]
